### ISSUE TITLE
UnboundLocalVariable Error while calculating gromacs energies for Benzene

### ISSUE THREAD

**Issue by umesh-timalsina** [openforcefield/openff-system#165]
Benzene sdf file attached below
```
benzene
     RDKit          3D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -1.1980    0.6518   -0.1262 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1736   -0.7195    0.0228 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0334   -1.3613    0.1484 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2134   -0.6392    0.1256 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1637    0.7219   -0.0235 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0222    1.3999   -0.1520 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1759    1.1115   -0.2214 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1191   -1.2744    0.0385 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0499   -2.4307    0.2644 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1520   -1.1673    0.2263 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1286    1.2398   -0.0344 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0521    2.4675   -0.2685 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
  1  7  1  0
  2  8  1  0
  3  9  1  0
  4 10  1  0
  5 11  1  0
  6 12  1  0
M  END
$$$$
```
Code to reproduce this behavior
```py
>>> from openff.system.components.foyer import from_foyer
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
>>> import foyer
>>> import mdtraj as md
>>> from simtk import unit as omm_unit
>>> from openff.system.tests.energy_tests.gromacs import get_gromacs_energies
>>> oplsaa = foyer.forcefields.load_OPLSAA()
>>> from openff.toolkit.topology import Topology, Molecule
>>> from openff.system.components.misc import OFFBioTop
>>> benzene = Molecule.from_file("path/to/benzene.sdf")
>>> biotop = OFFBioTop.from_molecules(benzene) 
>>> biotop.mdtop = md.Topology.from_openmm(biotop.to_openmm())
>>> system = from_foyer(ff=oplsaa, topology=biotop)
>>> system.box = [4, 4, 4]
>>> system.positions = benzene.conformers[0].value_in_unit(omm_unit.nanometer)
>>> get_gromacs_energies(system)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/work/mosdef-hub/colab/openff-system/openff/system/tests/energy_tests/gromacs.py", line 159, in get_gromacs_energies
    off_sys.to_top("out.top", writer=writer)
  File "/home/umesh/work/mosdef-hub/colab/openff-system/openff/system/components/system.py", line 119, in to_top
    to_top(self, file_path)
  File "/home/umesh/work/mosdef-hub/colab/openff-system/openff/system/interop/internal/gromacs.py", line 112, in to_top
    _write_valence(top_file, openff_sys)
  File "/home/umesh/work/mosdef-hub/colab/openff-system/openff/system/interop/internal/gromacs.py", line 308, in _write_valence
    _write_bonds(top_file, openff_sys)
  File "/home/umesh/work/mosdef-hub/colab/openff-system/openff/system/interop/internal/gromacs.py", line 329, in _write_bonds
    params = bond_handler.potentials[pot_key].parameters
UnboundLocalError: local variable 'pot_key' referenced before assignment
>>> 

```

**Comment by mattwthompson** [comment]
Thanks for posting this. I think the issue is inconsistent sorting of atom indices in the bonds 

```python3
In [26]: [(top_key.atom_indices[0], top_key.atom_indices[1]) for top_key in system['Bonds'].slot_map.keys()]
Out[26]:
[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 0),  # HERE
 (0, 6),
 (1, 7),
 (2, 8),
 (3, 9),
 (4, 10),
 (5, 11)]

In [27]: [(b.atom1.index, b.atom2.index) for b in biotop.mdtop.bonds]
Out[27]:
[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (0, 5),  # HERE
 (0, 6),
 (1, 7),
 (2, 8),
 (3, 9),
 (4, 10),
 (5, 11)]
```

My first guess is that the atom indices in the `TopologyKey` objects need to be sorted - let me see if that fixes it.

**Comment by mattwthompson** [comment]
Notably, it looks like MDTraj sorts bond indices, whereas the OpenFF Molecules currently do not. 

```python3
In [14]: [(b.atom1_index, b.atom2_index) for b in mol.bonds]
Out[14]:
[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 0),
 (0, 6),
 (1, 7),
 (2, 8),
 (3, 9),
 (4, 10),
 (5, 11)]

In [15]: [(b.atom1.index, b.atom2.index) for b in mdtop.bonds]
Out[15]:
[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (0, 5),
 (0, 6),
 (1, 7),
 (2, 8),
 (3, 9),
 (4, 10),
 (5, 11)]
```
SMIRNOFF-style typing takes place on the Molecules and the export iterates over the topology, so the lookup ~~failed~~ would have failed if it was typed SMIRNOFF-style, but it's typed Foyer-style. BUT, `foyer.TopologyGraph` at some point sorted the indices:
```python3
In [23]: [*top_graph.edges]
Out[23]:
[(0, 1),
 (0, 5),
 (0, 6),
 (1, 2),
 (1, 7),
 (2, 3),
 (2, 8),
 (3, 4),
 (3, 9),
 (4, 5),
 (4, 10),
 (5, 11)]
